/**
 * The landmark materials of the export: one shared set (`lm_*`) for every landmark family, written as material
 * definitions in the manifest's `materialDefs` (the world compiler's shape, read by the Unreal importer's
 * evren_surfaces.py: baseColorFactor, baseColor / normal / orm files, tiling in metres, roughness, metallic, alphaMode).
 *
 * The web shades landmarks with procedural shaders; here every surface gets an approved texture set (the world
 * compiler's TextureBaker, so files are named and processed exactly as the street tiles' and Unreal imports each once)
 * or a flat PBR colour.
 *
 * Colour: `tinted` materials take their colour from COLOR_0 (the builders' per-vertex tint, times ambient occlusion);
 * their texture only adds relative detail, so the baseColorFactor divides it by its mean linear colour. The other
 * materials keep the texture's own colour (brick, roof tiles, asphalt) or a flat colour; COLOR_0 then carries only AO.
 */
import { copyFileSync, existsSync, mkdirSync } from 'node:fs';
import { basename, join } from 'node:path';
import sharp from 'sharp';
import { defineMaterials, type TextureSetRef } from '../../world-compiler/src/materials';
import { TextureBaker } from '../../world-compiler/src/textures';

export interface LandmarkMaterial {
  id: string;
  /** Approved texture set (world compiler registry form). */
  textures?: TextureSetRef;
  /** A texture generated by the exporter (composite.ts) instead of a set. */
  generated?: GeneratedSet;
  /** Metres per texture repeat. */
  tiling?: [number, number];
  /** Linear colour: flat colour, or the factor on the texture (untinted), or a multiplier (tinted). */
  color?: [number, number, number];
  tinted: boolean;
  roughness: number;
  metallic?: number;
  alphaMode?: 'OPAQUE' | 'MASK';
  doubleSided?: boolean;
}

export interface GeneratedSet {
  baseColor: string;
  normal?: string;
  orm?: string;
  /** The base colour stores colour x this (so values above 1 fit into 8 bits); the factor divides it out. */
  scale: number;
}

const STONE: TextureSetRef = { public: 'stone' };
const PLASTER: TextureSetRef = { public: 'plaster' };

/** Every landmark material; families map their surface ids onto these ids (sources.ts). */
export const LANDMARK_MATERIALS: LandmarkMaterial[] = [
  // Masonry, tinted by the builders' colours.
  { id: 'lm_stone', textures: STONE, tiling: [2.2, 2.2], tinted: true, roughness: 0.95 },
  { id: 'lm_stone_fine', textures: STONE, tiling: [1.5, 1.5], tinted: true, roughness: 0.9 },
  { id: 'lm_plaster', textures: PLASTER, tiling: [2, 2], tinted: true, roughness: 1 },
  { id: 'lm_marble', textures: { asset: 'Marble019' }, tiling: [2, 2], tinted: true, roughness: 0.55 },
  { id: 'lm_rubble', textures: { asset: 'Rocks025' }, tiling: [1.9, 1.9], tinted: true, roughness: 1 },
  { id: 'lm_wall_stone', textures: { asset: 'Bricks102' }, tiling: [4.8, 2.4], tinted: true, roughness: 1 },
  { id: 'lm_concrete', textures: { public: 'concrete' }, tiling: [2.7, 2.7], tinted: true, roughness: 1 },
  { id: 'lm_paving', textures: { asset: 'granite_tile_04' }, tiling: [2, 2], tinted: true, roughness: 0.9 },
  // Textures with their own colour.
  { id: 'lm_brick', textures: { public: 'brick' }, tiling: [1, 1], tinted: false, roughness: 1 },
  { id: 'lm_wall_brick', textures: { asset: 'castle_brick_broken_06' }, tiling: [3, 3.3], tinted: false, roughness: 1 },
  { id: 'lm_roof_tiles', textures: { public: 'roof_tiles' }, tiling: [2.5, 2.5], tinted: false, roughness: 1 },
  { id: 'lm_road', textures: { asset: 'asphalt_02' }, tiling: [4, 4], tinted: false, roughness: 1 },
  { id: 'lm_grass', textures: { asset: 'Grass004' }, tiling: [2, 2], tinted: false, roughness: 1 },
  { id: 'lm_foliage', textures: { asset: 'LeafSet029' }, tiling: [0.75, 0.75], color: [0.55, 0.62, 0.45], tinted: false, roughness: 0.7, alphaMode: 'MASK', doubleSided: true },
  // Flat, tinted.
  { id: 'lm_steel', tinted: true, roughness: 0.5 },
  { id: 'lm_metal', tinted: true, roughness: 0.42, metallic: 0.6 },
  { id: 'lm_paint', tinted: true, roughness: 0.5 },
  { id: 'lm_slate', tinted: true, roughness: 0.48 },
  { id: 'lm_granite', tinted: true, roughness: 0.42 },
  { id: 'lm_bronze', tinted: true, roughness: 0.55, metallic: 0.55 },
  { id: 'lm_iron', tinted: true, roughness: 0.5, metallic: 0.5 },
  { id: 'lm_wood', tinted: true, roughness: 0.75 },
  { id: 'lm_dark', tinted: true, roughness: 0.65 },
  { id: 'lm_clock', tinted: true, roughness: 0.35 },
  { id: 'lm_cable', tinted: true, roughness: 0.4, metallic: 0.6 },
  { id: 'lm_curtain_glass', tinted: true, roughness: 0.06, metallic: 0.75 },
  // Flat, absolute colour.
  { id: 'lm_lead', color: [0.19, 0.2, 0.215], tinted: false, roughness: 0.58, metallic: 0.25 },
  { id: 'lm_gold', color: [1, 0.74, 0.32], tinted: false, roughness: 0.24, metallic: 1 },
  { id: 'lm_window', color: [0.018, 0.02, 0.023], tinted: false, roughness: 0.08 },
  { id: 'lm_lamp', color: [0.8, 0.78, 0.72], tinted: false, roughness: 0.35 },
  { id: 'lm_void', color: [0.03, 0.027, 0.024], tinted: false, roughness: 1 },
];

export interface MaterialRecord {
  id: string;
  baseColorFactor: [number, number, number, number];
  baseColor: string | null;
  normal: string | null;
  orm: string | null;
  tiling: [number, number];
  roughness: number;
  metallic: number;
  alphaMode: 'OPAQUE' | 'MASK';
  doubleSided: boolean;
  tinted: boolean;
}

const r4 = (v: number): number => Math.round(v * 10000) / 10000;
const toLinear = (c: number): number => (c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4));

/** Mean linear RGB of an sRGB image (sampled on a 128 px thumbnail). */
async function meanLinear(file: string): Promise<[number, number, number]> {
  const { data, info } = await sharp(file).resize(128, 128, { fit: 'fill' }).removeAlpha().raw().toBuffer({ resolveWithObject: true });
  const sum = [0, 0, 0];
  const lut = Array.from({ length: 256 }, (_, i) => toLinear(i / 255));
  for (let i = 0; i < data.length; i += info.channels) {
    sum[0] += lut[data[i]];
    sum[1] += lut[data[i + 1]];
    sum[2] += lut[data[i + 2]];
  }
  const n = data.length / info.channels;
  return [sum[0] / n, sum[1] / n, sum[2] / n];
}

/**
 * Bakes the textures of the used materials into <out>/textures/ and returns their records (only `used` ids, in
 * table order).
 */
export async function materialRecords(outDir: string, used: ReadonlySet<string>, extra: readonly LandmarkMaterial[] = []): Promise<MaterialRecord[]> {
  const all = [...LANDMARK_MATERIALS, ...extra].filter((m) => used.has(m.id));
  defineMaterials(all.filter((m) => m.textures).map((m) => ({ id: m.id, color: 0xffffff, textures: m.textures, tiling: m.tiling, alphaMode: m.alphaMode, replace: true })));
  const baker = bakerFor(outDir);
  const out: MaterialRecord[] = [];
  for (const m of all) {
    let baseColor: string | null = null;
    let normal: string | null = null;
    let orm: string | null = null;
    let factor: [number, number, number] = m.color ?? [1, 1, 1];
    if (m.textures) {
      const set = await baker.material(m.id);
      if (!set) {
        throw new Error(`${m.id}: texture set unavailable (${[...baker.problems].map(([k, v]) => `${k}: ${v}`).join('; ')})`);
      }
      baseColor = set.baseColor ? `textures/${set.baseColor.file}` : null;
      normal = set.normal ? `textures/${set.normal.file}` : null;
      orm = set.orm ? `textures/${set.orm.file}` : null;
      if (m.tinted && baseColor) {
        const mean = await meanLinear(join(outDir, baseColor));
        factor = [factor[0] / mean[0], factor[1] / mean[1], factor[2] / mean[2]];
      }
    } else if (m.generated) {
      mkdirSync(join(outDir, 'textures'), { recursive: true });
      const put = (file: string | undefined): string | null => {
        if (!file) return null;
        const dst = join(outDir, 'textures', basename(file));
        if (!existsSync(dst)) copyFileSync(file, dst);
        return `textures/${basename(file)}`;
      };
      baseColor = put(m.generated.baseColor);
      normal = put(m.generated.normal);
      orm = put(m.generated.orm);
      factor = [factor[0] / m.generated.scale, factor[1] / m.generated.scale, factor[2] / m.generated.scale];
    }
    out.push({
      id: m.id,
      baseColorFactor: [r4(factor[0]), r4(factor[1]), r4(factor[2]), 1],
      baseColor,
      normal,
      orm,
      tiling: m.tiling ?? [2, 2],
      roughness: m.roughness,
      metallic: m.metallic ?? 0,
      alphaMode: m.alphaMode ?? 'OPAQUE',
      doubleSided: m.doubleSided ?? false,
      tinted: m.tinted,
    });
  }
  return out;
}

/** Whether a material takes its colour from COLOR_0. */
export function isTinted(id: string, extra: readonly LandmarkMaterial[] = []): boolean {
  return ([...LANDMARK_MATERIALS, ...extra].find((m) => m.id === id) ?? { tinted: true }).tinted;
}

const bakers = new Map<string, TextureBaker>();
function bakerFor(outDir: string): TextureBaker {
  let b = bakers.get(outDir);
  if (!b) {
    b = new TextureBaker(outDir);
    bakers.set(outDir, b);
  }
  return b;
}

/** Bakes one approved set (as the street tiles do) and returns its files, for the composites (composite.ts). */
export async function bakeSet(outDir: string, id: string, textures: TextureSetRef, tiling: [number, number]): Promise<{ color: string; normal?: string; orm?: string; tiling: [number, number] }> {
  defineMaterials([{ id, color: 0xffffff, textures, tiling, replace: true }]);
  const set = await bakerFor(outDir).material(id);
  if (!set?.baseColor) {
    throw new Error(`${id}: texture set unavailable`);
  }
  const at = (f?: { file: string }): string | undefined => (f ? join(outDir, 'textures', f.file) : undefined);
  return { color: at(set.baseColor)!, normal: at(set.normal), orm: at(set.orm), tiling };
}
