/**
 * Builds the Seventeen Skies identity files from the code that draws them (src/ui/brand.ts, src/ui/brand-logo.ts):
 *
 *   npm run brand        SVGs, colour tokens and the web manifest, plus scripts/brand/renders.json
 *   npm run brand:png    the PNG / JPG renders listed in renders.json (snap.mjs, dev server on 5199)
 *
 * public/brand/      what the game's page serves: favicons, app icons, manifest, share image
 * .docs/brand/kit/   the brand kit for everything else: logos, monogram, social images, colours
 * Guide: .docs/brand/README.md.
 */
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { BRAND, BRAND_COLORS } from '../../src/ui/brand';
import { monogramSvg, titleLogoSvg } from '../../src/ui/brand-logo';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const PUBLIC = 'public/brand';
const KIT = '.docs/brand/kit';

function write(rel: string, body: string): void {
  const path = join(ROOT, rel);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, body.endsWith('\n') ? body : body + '\n');
  console.log(rel);
}

// --- SVG ---------------------------------------------------------------------------------------------------
write(`${PUBLIC}/favicon.svg`, monogramSvg({ id: 'ss', radius: 0.2 }));
write(`${PUBLIC}/icon.svg`, monogramSvg({ id: 'ss' }));
write(`${KIT}/svg/logo.svg`, titleLogoSvg({ id: 'ss' }));
write(`${KIT}/svg/logo-title.svg`, titleLogoSvg({ id: 'ss', crest: false }));
write(`${KIT}/svg/monogram.svg`, monogramSvg({ id: 'ss', tile: false }));
write(`${KIT}/svg/monogram-tile.svg`, monogramSvg({ id: 'ss' }));
// Earlier builds wrote the logos to public/; they now live in the kit only.
for (const stale of ['logo.svg', 'logo-title.svg']) {
  rmSync(join(ROOT, PUBLIC, stale), { force: true });
}

// --- Tokens and manifest -----------------------------------------------------------------------------------
write(`${KIT}/colors.json`, JSON.stringify(BRAND_COLORS, null, 2));
write(
  `${KIT}/colors.css`,
  `/* ${BRAND.name} colour tokens (generated by scripts/brand/build-brand.ts from src/ui/brand.ts). */\n:root {\n` +
    Object.entries(BRAND_COLORS)
      .map(([k, v]) => `  --ss-${k.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase())}: ${v};`)
      .join('\n') +
    '\n}',
);
write(
  `${PUBLIC}/site.webmanifest`,
  JSON.stringify(
    {
      name: BRAND.name,
      short_name: BRAND.name,
      description: BRAND.descriptionTr,
      lang: 'tr',
      start_url: '../',
      scope: '../',
      display: 'fullscreen',
      orientation: 'landscape',
      background_color: BRAND_COLORS.night,
      theme_color: BRAND_COLORS.night,
      icons: [
        { src: 'icon-192.png', sizes: '192x192', type: 'image/png' },
        { src: 'icon-512.png', sizes: '512x512', type: 'image/png' },
        { src: 'icon.svg', sizes: 'any', type: 'image/svg+xml' },
      ],
    },
    null,
    2,
  ),
);

// --- Raster jobs for snap.mjs --------------------------------------------------------------------------------
interface Job {
  url: string;
  out: string;
  w: number;
  h: number;
  transparent?: boolean;
}
const page = '/sandbox/brand.html';
const logoHeight = (w: number, crest: boolean): number =>
  Math.ceil(Number(/height="([\d.]+)"/.exec(titleLogoSvg({ width: w, crest }))![1]));
const logo = (w: number, crest: boolean, out: string): Job => ({
  url: `${page}?show=logo&w=${w}${crest ? '' : '&crest=0'}`,
  out,
  w,
  h: logoHeight(w, crest),
  transparent: true,
});
const icon = (size: number, out: string, extra = '', transparent = true): Job => ({
  url: `${page}?show=icon&size=${size}${extra}`,
  out,
  w: size,
  h: size,
  transparent,
});
const jobs: Job[] = [
  // Served by the game's page.
  icon(32, `${PUBLIC}/favicon-32.png`, '&radius=0.2'),
  icon(192, `${PUBLIC}/icon-192.png`),
  icon(512, `${PUBLIC}/icon-512.png`),
  icon(180, `${PUBLIC}/apple-touch-icon.png`, '&radius=0', false),
  { url: `${page}?show=og`, out: `${PUBLIC}/og.jpg`, w: 1200, h: 630 },
  // Kit.
  logo(2400, true, `${KIT}/png/logo-2400.png`),
  logo(1200, true, `${KIT}/png/logo-1200.png`),
  logo(600, true, `${KIT}/png/logo-600.png`),
  logo(1200, false, `${KIT}/png/logo-title-1200.png`),
  logo(600, false, `${KIT}/png/logo-title-600.png`),
  icon(1024, `${KIT}/png/monogram-1024.png`, '&tile=0'),
  icon(1024, `${KIT}/png/monogram-tile-1024.png`),
  icon(512, `${KIT}/png/monogram-tile-512.png`),
  icon(400, `${KIT}/social/avatar-400.png`, '&radius=0', false),
  { url: `${page}?show=banner`, out: `${KIT}/social/banner-1500x500.jpg`, w: 1500, h: 500 },
  { url: `${page}?show=og`, out: `${KIT}/social/og-1200x630.jpg`, w: 1200, h: 630 },
  { url: page, out: '.docs/brand/brand-sheet.jpg', w: 1200, h: 900 },
];
write('scripts/brand/renders.json', JSON.stringify(jobs, null, 2));
