#!/usr/bin/env python3
"""
Writes .docs/assets/archive-78rpm.md, the catalogue of the archived historic 78 rpm recordings, from
tools/assets/approved.json (kind 'recording') and tools/assets/moment-pieces.report.json. Edit those, not the doc.

    python3 scripts/data/archive-78rpm-doc.py
"""
import json
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
APPROVED = os.path.join(ROOT, 'tools/assets/approved.json')
REPORT = os.path.join(ROOT, 'tools/assets/moment-pieces.report.json')
RECIPES = os.path.join(ROOT, 'tools/assets/moment-pieces.json')
OUT = os.path.join(ROOT, '.docs/assets/archive-78rpm.md')
COPIES = 'data/archive/78rpm'

SOURCE = {'loc': 'Library of Congress, National Jukebox', 'commons': 'Wikimedia Commons', 'analogion': 'analogion.com',
          'internet-archive': 'Internet Archive', 'gallica': 'Gallica (BnF), Archives de la Parole'}
RISK = {'clean': 'clean', 'us-risky': '**US-risky**'}


def cell(t):
    return str(t if t is not None else '').replace('|', '\\|').replace('\n', ' ')


def label_line(rec):
    label, cat = rec.get('label') or '', rec.get('catalogue') or ''
    head = cat if cat.startswith(label) else ' '.join(x for x in (label, cat) if x)
    return head + (f", matrix {rec['matrix']}" if rec.get('matrix') else '')


def mb(n):
    return f'{n / 1e6:.1f} MB' if n else '–'


def main():
    recs = [a for a in json.load(open(APPROVED, encoding='utf-8'))['assets'] if a.get('kind') == 'recording']
    report = json.load(open(REPORT, encoding='utf-8'))['pieces'] if os.path.exists(REPORT) else {}
    recipes = {p['id']: p for p in json.load(open(RECIPES, encoding='utf-8'))['pieces']}
    by_rec = {}
    for pid, p in recipes.items():
        by_rec.setdefault(p['recording'], []).append(pid)

    total = sum(f.get('bytes') or 0 for r in recs for f in r['files'])
    missing = [r['id'] for r in recs if any(not f.get('sha256') for f in r['files'])]
    clean = [r for r in recs if r['risk'] == 'clean']
    risky = [r for r in recs if r['risk'] != 'clean']

    rows = []
    for r in recs:
        rec = r['recording']
        files = '<br>'.join(
            f"`{cell(f['name'])}` ({cell(f['format'])}, {mb(f.get('bytes'))}, sha256 `{(f.get('sha256') or 'not yet downloaded')[:12]}`)"
            + (f" — {cell(f['side'])}" if f.get('side') else '')
            for f in r['files'])
        copy = os.path.join(ROOT, COPIES, r['id'])
        where = f"`assets-src/audio/78rpm/{r['id']}/`" + (f"<br>git copy: `{COPIES}/{r['id']}/`" if os.path.isdir(copy) else '')
        pieces = ', '.join(f'`{p}`' for p in by_rec.get(r['id'], [])) or 'archive only'
        rows.append(' | '.join([
            cell(r['candidate']), cell(rec['title_tr']), cell(rec['performers']),
            cell(label_line(rec)),
            cell(rec.get('published')), f"[{SOURCE[r['source']]}]({r['url']})", RISK[r['risk']], files, where, pieces,
        ]))

    rights = []
    for r in recs:
        rec = r['recording']
        rg = rec['rights']
        extra = ''
        if rec.get('catalogue_record'):
            extra = f"\n- BnF catalogue record: <{rec['catalogue_record']}>; shelfmark: {rec.get('shelfmark', '')}."
        rights.append(f"""### {rec['title_tr']} (`{r['id']}`)

- Candidate {r['candidate']} in [moment-music.md](candidates/moment-music.md); {RISK[r['risk']]}; licence value `{r['licence']}`.
- Performers: {rec['performers']}. Label: {label_line(rec) or '–'}. Recorded / published: {rec.get('recorded') or rec.get('published')}, {rec.get('place', '')}.
- Archive page: <{r['url']}>. Transfer: {rec['transfer']}.
- About: {rec['summary']}
- US: {rg['us']}
- Turkey: {rg['tr']}
- Composition / performance: {rg['composition']}
- Note: {rg['note']}
- Credit line: {r['attribution']}{extra}
""")

    pieces = []
    for pid, res in report.items():
        m = res['metrics']
        c = m['compare']
        rp = recipes.get(pid, {})
        pieces.append(' | '.join([
            f'`{pid}`', f"`{res['recording']}`", f"{res['segment'][0]}–{res['segment'][1]} s", rp.get('target', ''),
            f"{m['raw']['snr_db']} → {m['denoised']['snr_db']} dB (+{m['snrGainDb']})",
            f"{m['raw']['clicks_per_s']} → {m['denoised']['clicks_per_s']}",
            f"{m['raw']['flatness_quiet']} → {m['denoised']['flatness_quiet']}",
            f"{c['kurtosis_ratio']}", f"{c['band_change_db']} / {c['hf_change_db']}", f"{c['hiss_change_db']}",
            f"**{res['variant']}**" + (f" ({'; '.join(res['autoReasons'])})" if res['autoReasons'] else ''),
        ]))

    md = f"""# Archive of historic 78 rpm recordings

Generated by `scripts/data/archive-78rpm-doc.py` from [`tools/assets/approved.json`](../../tools/assets/approved.json)
(kind `recording`) and [`tools/assets/moment-pieces.report.json`](../../tools/assets/moment-pieces.report.json). Edit
those, not this file.

The owner approved on **2026-09-26** ([decision](candidates/moment-music.md#decision-2026-09-26)) that every candidate
recording of [moment-music.md](candidates/moment-music.md) is archived in its original form with its source preserved
("bizde kalsınlar, kaynaklarını da koru"), including the ones that are public domain in Turkey but not yet in the US.
Later work only opens, copies or trims them; the originals stay untouched.

- **{len(recs)} recordings, {sum(len(r['files']) for r in recs)} files, {mb(total)}**: {len(clean)} clean, {len(risky)} US-risky.
{('- Not yet downloaded (sha256 pending): ' + ', '.join(f'`{m}`' for m in missing) + '. upload.wikimedia.org answered every request with HTTP 429 on 2026-09-26; rerun `node scripts/data/fetch-assets.mjs --kind=recording --no-docs --write-sha` later.') if missing else '- Every file is downloaded and hashed.'}
- **Where the originals live:** `assets-src/audio/78rpm/<id>/` (gitignored) with a `source.json` stamp. Any machine
  re-downloads the exact files with `node scripts/data/fetch-assets.mjs --kind=recording --no-docs`, which verifies
  each file against the sha256 recorded in `approved.json` (a mismatch means the archive changed the file: check it
  before touching the manifest).
- **Committed copies:** raw WAVs are never committed (30–38 MB each). The small, clean originals from the least durable
  source (analogion.com, a personal site) are also kept in git, byte for byte, in `{COPIES}/<id>/`. US-risky
  originals are never committed, whatever their size.
- **US-risky recordings** (public domain in Turkey, still protected in the US: the 1949 Kâtibim, the Pathé Istanbul
  discs of about 1927–1928, the Darülelhan series, the undated Hafız Burhan sides) may reach players only through
  `private-assets/` and builds, never `public/` or the repository ([private-assets.md](private-assets.md)). The owner
  accepts that residual risk; each one carries full attribution. **Takedown requests: `<contact-email>`.**
- Gallica files: the BnF marks them "domaine public" but attaches reuse conditions to its own files (non-commercial
  reuse free with the credit "Source gallica.bnf.fr / BnF"; commercial reuse needs a BnF licence). Settle this before
  any paid release.

## Catalogue

| Cand. | Title | Performers | Label / catalogue | Published | Source | Rights | Original files | Where | Moment pieces |
|---|---|---|---|---|---|---|---|---|---|
{chr(10).join(f'| {r} |' for r in rows)}

## Moment pieces made from the archive

Built by `scripts/audio/prep-moment-music.py` (restoration chain and metrics: `scripts/audio/restore78.py`). Nobody
could listen in the build container, so the default version is chosen from objective metrics: SNR = music level
(p70 of 50 ms frames) minus the groove noise; flatness = spectral flatness of the quietest 10 % of frames; kurtosis
ratio = log power-spectrum kurtosis of the groove after / before the hiss stage (musical noise, the "metallic"
artefact, raises it; < 1 passes); band / HF = change of the music's own power (loud frames minus groove) in 300 Hz–3 kHz
and 3–6 kHz after the dehiss stage (pass: within ±1.5 dB, and no more than −3 dB); hiss = groove change in 5–10 kHz.
Denoised is the default only when the SNR gain is at least 3 dB and every artefact heuristic passes; otherwise raw.
Both versions ship; `?music=raw` / `?music=denoised` plays the other one.

| Piece | Recording | Segment | Target | SNR raw → denoised | Clicks/s | Quiet flatness | Kurtosis ratio | Band / HF (dB) | Hiss (dB) | Default |
|---|---|---|---|---|---|---|---|---|---|---|
{chr(10).join(f'| {p} |' for p in pieces)}

## Checks made on specific recordings

- **Nafpliotis, Apolytikion of St George (H13): no later drone found.** analogion.com says the isokratema (ison) on some
  Nafpliotis tracks was overdubbed decades later by Konstantinos Katsoulis and that the original discs had none. An
  objective drone test (16k-FFT peaks 70–450 Hz per 186 ms frame; a drone is a pitch held unbroken under the moving
  melody) found no sustained low pitch: the most frequent one (163 Hz, the chant's own reciting tone) never lasts longer
  than 1.5 s unbroken, and no pitch at all holds 4 s. The Trisagion and Tin oraiotita transfers behave the same
  (longest steady pitch 3.3 s). The file is a processed transfer ("offered by B. Stavropoulos": declicked,
  band-limited to about 5 kHz), which adds no rights of its own. **Confirm by ear** before release.
- **Kâğıthane Semaisi (H1):** the instrumental introduction actually starts at about 0:01.5 and the voice enters at
  about 1:04.5; the owner's cut 0:08–1:03 was kept (0:07.5–1:03.5 with fades). The first six seconds are available if a
  longer piece is wanted.
- **Safiye Ayla, Kâtibim:** the Internet Archive upload has gated (digitally silent) head and tail and no groove
  run-in, so its noise profile is the quietest music-free second; the transfer seems already filtered, which is why
  the denoise gains little.
- **Pathé sides:** the side order (f1 / f2) follows the order of the BnF title ("Husseyni Taxim ; Huzam Taxim" = side
  1 Hüseyni, side 2 Hüzzam) and was not verified by ear.
- **Refik Bey's Saz Semaisi (H20):** if it is Tanburi Refik (Fersan) Bey's own composition (he died in 1965), Turkey
  protects the composition until the end of 2035: check before any use.

## Rights and provenance per recording

{chr(10).join(rights)}"""
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(md)
    print('wrote', os.path.relpath(OUT, ROOT))


if __name__ == '__main__':
    main()
