/**
 * Heritage site footprints from the OSM data the game ships: for every heritage landmark with a 'polygon' footprint
 * (today the Topkapı Sarayı), the OSM buildings of the flight-scale regions whose centroid lies inside the polygon,
 * written as lat/lon rings with their name and courtyard holes (src/world/landmarks/heritage/data/<id>.ts). The site
 * builder decides the building type from the name.
 *
 *   npx tsx scripts/data/heritage-footprints.ts
 *
 * Data © OpenStreetMap contributors, ODbL 1.0.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { latLonToLocal, localToLatLon } from '../../src/core/geo-coords';
import { LANDMARKS } from '../../src/world/geo/data/landmarks';

const ROOT = resolve(import.meta.dirname, '../..');
const REGIONS = resolve(ROOT, 'public/data/osm/regions');

interface Building {
  id: number;
  ring: number[];
  holes?: number[][];
  name?: string;
  kind?: string;
}

function inside(poly: [number, number][], x: number, z: number): boolean {
  let c = false;
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
    const [xi, zi] = poly[i];
    const [xj, zj] = poly[j];
    if (zi > z !== zj > z && x < ((xj - xi) * (z - zi)) / (zj - zi) + xi) {
      c = !c;
    }
  }
  return c;
}

const ll = (flat: readonly number[]): number[] => {
  const out: number[] = [];
  for (let i = 0; i + 1 < flat.length; i += 2) {
    const p = localToLatLon(flat[i], flat[i + 1]);
    out.push(Math.round(p.lat * 1e6) / 1e6, Math.round(p.lon * 1e6) / 1e6);
  }
  return out;
};

const buildings = new Map<number, Building>();
for (const f of readdirSync(REGIONS)) {
  const data = JSON.parse(readFileSync(resolve(REGIONS, f), 'utf8')) as { buildings?: Building[] };
  for (const b of data.buildings ?? []) {
    if (b.ring) {
      buildings.set(b.id, b);
    }
  }
}

for (const l of LANDMARKS) {
  if (l.builder !== 'heritage' || l.footprint !== 'polygon' || !l.footprintPolygon) {
    continue;
  }
  const poly: [number, number][] = [];
  for (let i = 0; i + 1 < l.footprintPolygon.length; i += 2) {
    const p = latLonToLocal(l.footprintPolygon[i], l.footprintPolygon[i + 1]);
    poly.push([p.x, p.z]);
  }
  const picked = [...buildings.values()].filter((b) => {
    let cx = 0;
    let cz = 0;
    const n = b.ring.length / 2;
    for (let i = 0; i < b.ring.length; i += 2) {
      cx += b.ring[i];
      cz += b.ring[i + 1];
    }
    return inside(poly, cx / n, cz / n);
  });
  picked.sort((a, b) => a.id - b.id);
  const name = l.id.replace(/-(sarayi|gari|kislasi)$/, '');
  const constName = `${name.toUpperCase().replace(/-/g, '_')}_FOOTPRINTS`;
  const lines = picked.map((b) => {
    const parts = [`key: '${b.id}'`, `ll: [${ll(b.ring).join(', ')}]`];
    if (b.name) {
      parts.push(`name: ${JSON.stringify(b.name)}`);
    }
    if (b.kind && b.kind !== 'yes') {
      parts.push(`kind: '${b.kind}'`);
    }
    if (b.holes?.length) {
      parts.push(`holes: [${b.holes.map((h) => `[${ll(h).join(', ')}]`).join(', ')}]`);
    }
    return `  { ${parts.join(', ')} },`;
  });
  const out = `/**
 * ${l.name}: the OSM buildings inside the landmark polygon (generated by scripts/data/heritage-footprints.ts; do
 * not edit by hand). Flat lat, lon pairs, open rings. © OpenStreetMap contributors, ODbL 1.0.
 */
import type { NamedFootprint } from './types';

export const ${constName}: readonly NamedFootprint[] = [
${lines.join('\n')}
];
`;
  writeFileSync(resolve(ROOT, `src/world/landmarks/heritage/data/${name}.ts`), out);
  console.log(`${l.id}: ${picked.length} buildings -> data/${name}.ts`);
}
