/** Height of the rig origin (center of mass) above the ground when the dragon stands (feet at y = -this). */
export const STANDING_ROOT_HEIGHT = 2.2;

/** Default pose values. */
export const DEFAULT_POSE = {
  flapPhase: 0,
  flapAmplitude: 0,
  wingSpread: 1,
  wingSweep: 0,
  wingTwist: 0,
  neckYaw: 0,
  neckPitch: 0,
  jawOpen: 0,
  tailYaw: 0,
  tailPitch: 0,
  legsTuck: 1,
  walkPhase: 0,
  walkAmount: 0,
  breath: 0.3,
  riderLeanPitch: 0,
  riderLeanRoll: 0,
  riderReinLeft: 0,
  riderReinRight: 0,
  riderTuck: 0,
  riderUrge: 0,
  riderPoint: 0,
  riderCheer: 0,
  riderPet: 0,
  riderStand: 0,
  gazeRider: 0,
  groundY: Number.NaN,
  groundNx: 0,
  groundNz: 0,
  gait: 0,
  stride: 2.6,
  foreGround: 1,
  wingRaise: 0,
  heelLift: 0,
  legReach: 0,
  skid: 0,
  swim: 0,
  swimPhase: 0,
  swimStroke: 0,
};
